-- =============================================
-- Growing in Grace - Privacy-conscious analytics
-- Migration 003
-- =============================================

CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (event_name IN (
    'page_view',
    'lesson_view',
    'handout_download',
    'video_click',
    'curriculum_start',
    'signup_complete',
    'signin_complete'
  )),
  page_path TEXT NOT NULL CHECK (char_length(page_path) BETWEEN 1 AND 300),
  lesson_slug TEXT CHECK (
    lesson_slug IS NULL OR lesson_slug ~ '^lesson-[0-9]{2}$'
  ),
  session_id UUID NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  referrer_host TEXT CHECK (
    referrer_host IS NULL OR char_length(referrer_host) <= 200
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx
  ON public.analytics_events (created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_event_name_idx
  ON public.analytics_events (event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_lesson_slug_idx
  ON public.analytics_events (lesson_slug, created_at DESC)
  WHERE lesson_slug IS NOT NULL;

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.analytics_events FROM anon, authenticated;
GRANT SELECT ON public.analytics_events TO authenticated;

DROP POLICY IF EXISTS "Admins can view analytics" ON public.analytics_events;
CREATE POLICY "Admins can view analytics"
  ON public.analytics_events FOR SELECT
  USING (public.current_user_is_admin());

CREATE OR REPLACE FUNCTION public.track_analytics_event(
  p_event_name TEXT,
  p_page_path TEXT,
  p_lesson_slug TEXT DEFAULT NULL,
  p_session_id UUID DEFAULT NULL,
  p_referrer_host TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_event_name NOT IN (
    'page_view',
    'lesson_view',
    'handout_download',
    'video_click',
    'curriculum_start',
    'signup_complete',
    'signin_complete'
  ) THEN
    RAISE EXCEPTION 'Unsupported analytics event';
  END IF;

  IF p_page_path IS NULL OR char_length(p_page_path) NOT BETWEEN 1 AND 300 THEN
    RAISE EXCEPTION 'Invalid analytics page path';
  END IF;

  IF p_lesson_slug IS NOT NULL
     AND p_lesson_slug !~ '^lesson-[0-9]{2}$' THEN
    RAISE EXCEPTION 'Invalid lesson slug';
  END IF;

  INSERT INTO public.analytics_events (
    event_name,
    page_path,
    lesson_slug,
    session_id,
    user_id,
    referrer_host
  ) VALUES (
    p_event_name,
    left(p_page_path, 300),
    p_lesson_slug,
    COALESCE(p_session_id, gen_random_uuid()),
    auth.uid(),
    NULLIF(left(COALESCE(p_referrer_host, ''), 200), '')
  );
END;
$$;

REVOKE ALL ON FUNCTION public.track_analytics_event(TEXT, TEXT, TEXT, UUID, TEXT)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.track_analytics_event(TEXT, TEXT, TEXT, UUID, TEXT)
  TO anon, authenticated;
